[package]
name = "axiograph-example-industrial"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Industrial engineering example harness for Axiograph"
publish = false

[[bin]]
name = "axiograph-industrial-example"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axiograph-pathdb = { path = "../axiograph-pathdb" }
clap.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
